- name: app-setup
  ansible.builtin.role-setup:
    name: common
    tasks_from: app-setup

- name: nodejs server setup
  ansible.builtin.role-setup:
    name: common
    tasks_from: nodejs-server

- name: mongodb setup
  ansible.builtin.role-setup:
    name: common
    tasks_from: mongodb-setup

- name: systemctl service 
  ansible.builtin.role-setup:
    name: common
    tasks_from: systemd



